### ISSUE TITLE
Create Button missing from File/Receiving addresses popup

### ISSUE THREAD

**Issue by jpass022** [bytzcurrency/BYTZ#6]
This issue tracker is only for technical issues related to Bytz Core.

### Describe the issue
Create Button missing from File/Receiving addresses popup

### Can you reliably reproduce the issue?
yes

#### If so, please list the steps to reproduce below:
1. Open Receiving addresses window and there is no '+New' button to create a new address

### Expected behaviour
Tell us what should happen
There should be a '+New' create button

### Actual behaviour
Tell us what happens instead
There is no '+New' create button

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
Example of QT with 'New' button...
![image](https://user-images.githubusercontent.com/5889788/126193261-2d8f674d-23b4-4722-9b51-e2e06f98f9c5.png)

New Bytz QT without 'New' button...
![image](https://user-images.githubusercontent.com/5889788/126193502-7c52504b-24ab-48ae-bbe9-2546a4a48f92.png)

### What version of Bytz Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

Ubuntu 20.04
v0.2.0.0-372bed1c1-snap
/BYTZ Core:0.2.0.0/

Windows version also has same issue...

**Comment by jpass022** [comment]
I saw in CLI the was a 'createwallet "wallet_name"' command. I also tried that and nothing showed up in the GUI... I did import a private key and that worked as expected.

**Comment by celbalrai** [comment]
Thank you for using the issue tracker, and for running the Snap!

Bytz, like Dash 0.17 and Bitcoin 0.20, have put the functionality to create a new receiving address under the 'Receive' tab, where you can see the button 'Create new receiving address'.

As such, you're kindly invited to use that.
